### ISSUE TITLE
Scrolling up when CatalogPages are already deleted

### ISSUE THREAD

**Issue by Morosko** [filiph/state_experiments#4]
I've used this very beautiful piece of code and adopted it into my project. I used it for an infinite news feed. The problem I am facing now is, when you scroll down a few hundred posts the first will get deleted. When you then scroll up again, it has to reload the posts and the ListView will jump to the very first post in the loaded page, so it skips 10 posts. How would I go to implement the ListView staying at the current scrolling position and just add the loaded page above?

PS: Thanks for the awesome talk at Google I/O!

**Comment by filiph** [comment]
Hmm, I think I understand the general problem (underlying list changing while we scroll), but I have trouble understanding the details (e.g. why it skips exactly 10 posts and not less). What can I do to the current example here to reproduce the problem?

**Comment by Morosko** [comment]
It skips exactly 10 posts, because we define the page size in line 16 in the CatalogBloc as ` static const _productsPerPage = 10;`. If I would set this to one it would work, I guess, but then I would make 10 times more requests.

I think that if you would change the delay in `_requestPage` to 3 seconds or so, you would notice it. Just make sure to scroll down enough, so the first posts will get deleted.

**Comment by filiph** [comment]
Hi, I'm trying to reproduce the issue you're describing, but no luck so far.

Could you please download https://github.com/filiph/state_experiments/tree/issue4-repro and see if you can reproduce? If so, a detailed walkthrough, or — even better — a screencast, would help a lot.

**Comment by Morosko** [comment]
Hi, thank you for your help. I solved my problem. In your example appears a CircularProgressIndicator while loading the products. I skipped this part and returned only a SizedBox which didn't fill up any space. I created a placeholder and all is working like expected. 👍
